# Generated by Django 3.2.24 on 2024-02-26 08:22

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='user',
            name='ethereum_address',
            field=models.CharField(default=user.models.default_ethereum_address, max_length=42, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('M', 'Manufacturer'), ('D', 'Distributor'), ('R', 'Retailer'), ('C', 'Consumer')], default='C', max_length=1),
        ),
    ]
