# Generated by Django 3.2.24 on 2024-02-26 10:27

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20240226_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('place', models.CharField(max_length=30)),
                ('ethereum_address', models.CharField(default=user.models.default_ethereum_address, max_length=42, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('place', models.CharField(max_length=30)),
                ('ethereum_address', models.CharField(default=user.models.default_ethereum_address, max_length=42, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('place', models.CharField(max_length=30)),
                ('ethereum_address', models.CharField(default=user.models.default_ethereum_address, max_length=42, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('place', models.CharField(max_length=30)),
                ('ethereum_address', models.CharField(default=user.models.default_ethereum_address, max_length=42, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_id',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('I', 'Init'), ('M', 'Manufacture'), ('D', 'Distribution'), ('R', 'Retail'), ('S', 'sold')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='d_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='user.distributor'),
        ),
        migrations.AddField(
            model_name='product',
            name='m_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='user.manufacturer'),
        ),
        migrations.AddField(
            model_name='product',
            name='r_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='user.retailer'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.consumer'),
        ),
    ]
