# Generated by Django 3.2.24 on 2024-02-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20240226_1557'),
        ('user', '0005_auto_20240226_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
