# Generated by Django 3.2.24 on 2024-03-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='password',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
