# Generated by Django 3.2.24 on 2024-03-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_consumer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='password',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='password',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='retailer',
            name='password',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
