# Generated by Django 3.2.24 on 2024-02-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20240226_1557'),
        ('product', '0005_nft_details_redeem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.consumer'),
        ),
        migrations.AlterField(
            model_name='nft_details',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.consumer'),
        ),
        migrations.AlterField(
            model_name='shipping_address',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.consumer'),
        ),
    ]
